### ISSUE TITLE
Can you tell me where I can get the dataset??

### ISSUE THREAD

**Issue by JayTWWM** [manncodes/Avinashak-Crime-prediction#2]

**Comment by manncodes** [comment]
Hey, just uploaded the csv file. 👍

**Comment by JayTWWM** [comment]
Thanks a lot mate, can you also name the source?
As in from where have you taken the data?

**Comment by manncodes** [comment]
Don't remember the source, but it was taken from indore city police ig.

**Comment by JayTWWM** [comment]
Alright thanks mate!
